<?php
/**
	* importer.php
  * This page imports the .html pages generated by kss-node.
	* Scaffolding uses .kss- classes to prevent unwanted inheritance of project styles (or vice versa). 
	*
	* To use: read styleguide.md
  * 
*/

	// GLOBALS
	global $styleguide_section;
	global $styleguide_site_root;	
	global $styleguide_site_name;
	global $styleguide_path;
	global $styleguide_section_prefix;
	global $styleguide_munge_breadcrumbs;
	global $styleguide_munge_title;
	global $styleguide_viewport_width;		
	global $styleguide_css_path;
	global $styleguide_folder_path;
				
	// CLI args for documentation
	$styleguide_cli_source = $styleguide_site_root . $styleguide_css_path;
	$styleguide_cli_destination = $styleguide_site_root . $styleguide_folder_path . '/generated';
	$styleguide_cli_template = $styleguide_site_root . $styleguide_folder_path . '/template';	
			
	// generated path for documentation navigation
	$styleguide_generated_path = $styleguide_folder_path . '/generated/';		
	$styleguide_template_path = $styleguide_folder_path . '/template/';			
?>

<!-- START STYLEGUIDE -->

<!-- yup, stylesheets don't belong here, but it works ;-) -->
<!-- this stylesheet only styles the KSS scaffolding, demo text, and markdown index/overview page -->
<link rel="stylesheet" href="<?php echo $styleguide_template_path; ?>public/kss.css" />

<div class="kss-wrapper">

  <div class="kss-content-col">

    <h1 class="kss-main-title"><?php echo $styleguide_site_name; ?> Living Styleguide</h1>
    
    <?php				
                    
      if ( $styleguide_section ) {
        $source = $styleguide_site_root . $styleguide_generated_path . 'section-' . $styleguide_section . '.html';
      }
      else {
        $source = $styleguide_site_root . $styleguide_generated_path . 'index.html';
      }
  
  $content = file_get_contents( $source );
          
  $replacements = array(
	 "[{STYLEGUIDE_SITE_NAME}]" => $styleguide_site_name,
	 "[{STYLEGUIDE_PATH}]" => $styleguide_path,
	 "[{STYLEGUIDE_SECTION_PREFIX}]" => $styleguide_section_prefix,
	 "[{STYLEGUIDE_GENERATED_PATH}]" => $styleguide_generated_path,
	 "[{STYLEGUIDE_TEMPLATE_PATH}]" => $styleguide_template_path,
	 "[{STYLEGUIDE_MUNGE_BREADCRUMBS}]" => $styleguide_munge_breadcrumbs,
	 "[{STYLEGUIDE_MUNGE_TITLE}]" => $styleguide_munge_title,
	 "[{STYLEGUIDE_VIEWPORT_WIDTH}]" => $styleguide_viewport_width,
	 "[{STYLEGUIDE_CLI_SOURCE}]" => $styleguide_cli_source,
	 "[{STYLEGUIDE_CLI_DESTINATION}]" => $styleguide_cli_destination,
	 "[{STYLEGUIDE_CLI_TEMPLATE}]" => $styleguide_cli_template,
	 "[{STYLEGUIDE_FOLDER_PATH}]" => $styleguide_folder_path,
	 "[{STYLEGUIDE_FOLDER_PATH_ABSOLUTE}]" => $styleguide_site_root . $styleguide_folder_path
  );				
  
  $content = strtr( $content, $replacements );
  
  if ( ! $styleguide_section ) {
   echo ('<div id="styleguide-markdown">');
  }
  
  echo $content;
  
  if ( ! $styleguide_section ) {
   echo ('</div>');
  }	
    
    ?>
  </div>
  <!-- end kss-content-col -->

</div>
<!-- end kss-wrapper -->



<!-- END STYLEGUIDE -->
