<?php
/**
	* importer.php
  * This page imports the .html pages generated by kss-node.
	* Scaffolding uses .kss- classes to prevent unwanted inheritance of project styles (or vice versa). 
	*
	* To use: read styleguide.md
  * 
*/
				
	// GLOBALS
	// globals populated in project's custom PHP template
	global $styleguide_site_root;			
	global $styleguide_section;
	global $styleguide_folder_path;		
	
	// globals populated via automatically (OS X) or manually (Windows) generated kss_config.inc.php
	global $styleguide_site_name;			
	global $styleguide_path;
	global $styleguide_css_path;			
	global $styleguide_section_prefix;
	global $styleguide_munge_breadcrumbs;
	global $styleguide_munge_title;
	global $styleguide_viewport_width;		
	
	// globals populated below
	global $styleguide_generated_path;
	
	include( $styleguide_site_root . $styleguide_folder_path . '/template/importer_config.inc.php' );
	$styleguide_site_name = $kss_config['project_php_styleguide_site_name'];
	$styleguide_path = $kss_config['project_php_styleguide_path'];			
	$styleguide_css_path = $kss_config['project_php_styleguide_css_path'];	
	$styleguide_section_prefix = $kss_config['project_php_styleguide_section_prefix'];
	$styleguide_munge_breadcrumbs = $kss_config['project_php_styleguide_munge_breadcrumbs'];
	$styleguide_munge_title = $kss_config['project_php_styleguide_munge_title'];
	$styleguide_viewport_width = $kss_config['project_php_styleguide_viewport_width'];				
				
	// CLI args for documentation
	$styleguide_cli_source = $styleguide_site_root . $styleguide_css_path;
	$styleguide_cli_destination = $styleguide_site_root . $styleguide_folder_path . '/generated'; // to update
	$styleguide_cli_template = $styleguide_site_root . $styleguide_folder_path . '/template';	// to update
			
	// generated path for documentation navigation
	$styleguide_generated_path = $styleguide_folder_path . '/generated/';		
	$styleguide_template_path = $styleguide_folder_path . '/template/';			
?>

<!-- START STYLEGUIDE -->

<!-- yup, stylesheets don't belong here, but it works ;-) -->
<!-- this stylesheet only styles the KSS scaffolding, demo text, and markdown index/overview page -->
<link rel="stylesheet" type="text/css" href="<?php echo $styleguide_folder_path; ?>/template/public/kss.css" />
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Codystar">

<div class="kss-wrapper">

  <div class="kss-content-col">

    <h1 class="styleguide-main-title"><?php echo $styleguide_site_name; ?> Living Styleguide</h1>
    
    <?php				
                    
      if ( $styleguide_section ) {
        $source = $styleguide_site_root . $styleguide_generated_path . 'section-' . $styleguide_section . '.html';
      }
      else {
        $source = $styleguide_site_root . $styleguide_generated_path . 'index.html';
      }
  
  $content = file_get_contents( $source );
          
  $replacements = array(
	 "[{STYLEGUIDE_DOMAIN}]" => $_SERVER['HTTP_HOST'],
	 "[{STYLEGUIDE_SITE_NAME}]" => $styleguide_site_name,
	 "[{STYLEGUIDE_PATH}]" => $styleguide_path,
	 "[{STYLEGUIDE_SECTION_PREFIX}]" => $styleguide_section_prefix,
	 "[{STYLEGUIDE_GENERATED_PATH}]" => $styleguide_generated_path,
	 "[{STYLEGUIDE_TEMPLATE_PATH}]" => $styleguide_template_path,
	 "[{STYLEGUIDE_MUNGE_BREADCRUMBS}]" => $styleguide_munge_breadcrumbs,
	 "[{STYLEGUIDE_MUNGE_TITLE}]" => $styleguide_munge_title,
	 "[{STYLEGUIDE_VIEWPORT_WIDTH}]" => $styleguide_viewport_width,
	 "[{STYLEGUIDE_CLI_SOURCE}]" => $styleguide_cli_source,
	 "[{STYLEGUIDE_CLI_DESTINATION}]" => $styleguide_cli_destination,
	 "[{STYLEGUIDE_CLI_TEMPLATE}]" => $styleguide_cli_template,
	 "[{STYLEGUIDE_FOLDER_PATH}]" => $styleguide_folder_path,
	 "[{STYLEGUIDE_FOLDER_PATH_ABSOLUTE}]" => $styleguide_site_root . $styleguide_folder_path
  );				
  
  $content = strtr( $content, $replacements );
  
  if ( ! $styleguide_section ) {
   echo ('<div id="styleguide-markdown">');
  }
  
  echo $content;
  
  if ( ! $styleguide_section ) {
   echo ('</div>');
  }	
    
    ?>
  </div>
  <!-- end kss-content-col -->

</div>
<!-- end kss-wrapper -->



<!-- END STYLEGUIDE -->
